apps/administrar/urls.py
from django.conf.urls import url,include
from apps.administrar.views import *

urlpatterns = [
url(r'^inicio$',index,name='inicio'),
url(r'^tipoU$',tipoU,name='tipoUsuario'),
url(r'^eliminarTipo/(?P<idTipo>\d+)/$',eliminar,name='eliminarTipo'),
url(r'^habilitarTipo/(?P<idTipo>\d+)/$',habilitar,name='habilitarTipo'),

url(r'^faseCultivo$',faseLista,name='faseCultivo'),
url(r'^faseCultivoSiembra/(?P<idSiembra>\d+)/$',faseListaSiembra,name='faseCultivoSiembra'),
url(r'^siembra$',siembras,name='siembra'),

url(r'^listaUsuarios$',listaUsuarios,name='listaUsuarios'),
url(r'^bloquearUsuario/(?P<idusuario>\d+)/$',bloquearUsuario,name='bloquearUsuario'),

url(r'^listaUsuarioBloqueados$',usuariosBloqueados,name='usuariosBloqueados'),
url(r'^habilitarUsuario/(?P<idusuario>\d+)/$',habilitarUsuario,name='habilitarUsuario'),
url(r'^verUsuario/(?P<idusuario>\d+)/$',verUsuario,name='verusuario'),

url(r'^nuevaFase$',nuevaFase,name="nuevaFase"),

]

apps/login/urls.py
from django.conf.urls import url,include
from apps.login.views import *

urlpatterns = [
url(r'^$',login, name='log'),
url(r'^registrar$',registrar,name='registro'),
url(r'^logout$',logout,name='logout'),
]

apps/simular/urls.py
from django.conf.urls import url,include
from apps.simular.views import *

urlpatterns = [
url(r'^inicio',index,name='index'),
url(r'^nuevaSimulacion',nuevaSimulacion,name='nuevaSimulacion'),
]

simulador/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/',include('apps.administrar.urls',namespace='admi')),
    url(r'^simulador/',include('apps.simular.urls',namespace='simular')),
    url(r'^',include('apps.login.urls',namespace='login')),
]

templates/base/baseAdmin.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{%  block title %}Document{% endblock %}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">	
 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static "datatables.net/js/jquery.dataTables.min.js" %} "></script>
    <script type="text/javascript" src="{% static "datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>

</head>
<body>
{% block navbar %} 

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Administracion</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'admi:inicio'%}">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Administrar<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'admi:tipoUsuario'%}">tipo usuario</a></li>
            <li><a href="{% url 'admi:faseCultivo' %}">Fases de cultivo</a></li>
            <li><a href="{% url 'admi:siembra'%}">Cultivos</a></li>
          </ul>
        </li>
        <li><a href="{% url 'admi:listaUsuarios' %}">Listado de usuarios</a></li>
        <li><a href="{% url 'admi:usuariosBloqueados' %}">Usuarios bloqueados</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{user.email}}</a></li>
        <li><a href="{% url 'login:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

{% endblock %}


{% block content %}

{% endblock %}	

</body>
<footer>
{% block footer %}

{% endblock %}	
</footer>
</html>

templates/base/baseUsuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{%  block title %}Document{% endblock %}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">	
 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
{% block navbar %} 

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Simulador de siembra</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{%url 'simular:index'%}">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Administrar<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'simular:nuevaSimulacion'%}">Nueva Simulacion</a></li>
            <li><a href="#">Cultivos</a></li>
          </ul>
        </li>
        <li><a href="#">Listado de simulaciones</a></li>
        <li><a href="#">Configuracion</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{user.email}}</a></li>
        <li><a href="{%url 'login:logout'%}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>

{% endblock %}


{% block content %}

{% endblock %}	

</body>
<footer>
{% block footer %}

{% endblock %}	
</footer>
</html>