apps/administrar/urls.py
from django.conf.urls import url,include
from apps.administrar.views import *

urlpatterns = [
url(r'^inicio$',index,name='inicio'),
url(r'^tipoU$',tipoU,name='tipoUsuario'),
url(r'^eliminarTipo/(?P<idTipo>\d+)/$',eliminar,name='eliminarTipo'),
url(r'^habilitarTipo/(?P<idTipo>\d+)/$',habilitar,name='habilitarTipo'),

url(r'^faseCultivo$',faseLista,name='faseCultivo'),
url(r'^faseCultivoSiembra/(?P<idSiembra>\d+)/$',faseListaSiembra,name='faseCultivoSiembra'),
url(r'^siembra$',siembras,name='siembra'),

url(r'^listaUsuarios$',listaUsuarios,name='listaUsuarios'),
url(r'^bloquearUsuario/(?P<idusuario>\d+)/$',bloquearUsuario,name='bloquearUsuario'),

url(r'^listaUsuarioBloqueados$',usuariosBloqueados,name='usuariosBloqueados'),
url(r'^habilitarUsuario/(?P<idusuario>\d+)/$',habilitarUsuario,name='habilitarUsuario'),
url(r'^verUsuario/(?P<idusuario>\d+)/$',verUsuario,name='verusuario'),

url(r'^nuevaFase$',nuevaFase,name="nuevaFase"),

]

apps/login/urls.py
from django.conf.urls import url,include
from apps.login.views import *

urlpatterns = [
url(r'^$',login, name='log'),
url(r'^registrar$',registrar,name='registro'),
url(r'^logout$',logout,name='logout'),
]

simulador/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/',include('apps.administrar.urls',namespace='admi')),
    url(r'^simulador/',include('apps.simular.urls',namespace='simular')),
    url(r'^',include('apps.login.urls',namespace='login')),
]

apps/administrar/models.py
from django.db import models

class tipoUsuario(models.Model):
	descripcion = models.CharField(max_length=50)
	estado = models.IntegerField()
	def __str__(self):
		return self.descripcion

class usuario(models.Model):
	nombre = models.CharField(max_length=50)
	apellido = models.CharField(max_length=50)
	password = models.CharField(max_length=256)
	fechaNacimiento = models.DateField()
	sexo = models.CharField(max_length=9)
	email = models.CharField(max_length=250)
	tipoU = models.ForeignKey(tipoUsuario)
	estado = models.IntegerField()
	def __str__(self):
		return self.email

class siembra(models.Model):
	nombre = models.CharField(max_length=50)
	descripcion=models.CharField(max_length=100)
	estado = models.IntegerField()
	def __str__(self):
		return self.nombre

class faseCultivo(models.Model):
	etapa = models.CharField(max_length=50)
	descripcion = models.CharField(max_length=50)
	diasDuracion = models.IntegerField()
	hidricos = models.DecimalField(max_digits=5,decimal_places=2)
	siembra = models.CharField(max_length=50)
	estado = models.IntegerField()
	def __str__(self):
		return self.descripcion

class configuracion(models.Model):
	temperaturaMax = models.DecimalField(max_digits=5,decimal_places=2)
	temperaturaMin = models.DecimalField(max_digits=5,decimal_places=2)
	humedad = models.DecimalField(max_digits=6,decimal_places=2)
	altitud = models.DecimalField(max_digits=6,decimal_places=2)
	luminosidad = models.DecimalField(max_digits=5,decimal_places=2)
	distanciaLinea = models.DecimalField(max_digits=5,decimal_places=2)

class simulacion(models.Model):
	nombre = models.CharField(max_length=50)
	lineaSiembra = models.IntegerField()
	estado = models.IntegerField()
	siembra = models.ForeignKey(siembra,null=True,blank=False,on_delete=models.CASCADE)
	fase = models.ManyToManyField(faseCultivo)
	confi = models.OneToOneField(configuracion)
	usu = models.ForeignKey(usuario,null=True,blank=False)
	def __str__(self):
		return self.nombre

apps/login/models.py
from django.db import models

# Create your models here.

apps/administrar/views.py
from django.shortcuts import render,redirect
from apps.administrar.models import *
from django.views.decorators.csrf import csrf_exempt, csrf_protect


def index(request):
	return render(request,'simular/inicioAdmin.html')

@csrf_protect
def tipoU(request):
	if request.method == 'POST':
		tUsuario = tipoUsuario()
		tUsuario.descripcion = request.POST['descripcion']
		tUsuario.estado = 1
		tUsuario.save()
		return redirect('admi:tipoUsuario')
	tipo = tipoUsuario.objects.order_by('id')
	contexto =  {'tipo':tipo}
	return render(request,'administrar/tipoUsuario.html',contexto)

def eliminar(request,idTipo):
	tipo = tipoUsuario.objects.get(id=idTipo)
	tipo.estado = 0
	tipo.save()
	return redirect('admi:tipoUsuario')

def habilitar(request,idTipo):
	tipo = tipoUsuario.objects.get(id=idTipo)
	tipo.estado = 1
	tipo.save()
	return redirect('admi:tipoUsuario')

def faseLista(request):
	fase = faseCultivo.objects.all().order_by('id')
	return render(request,'administrar/faseCultivo.html',{'fase':fase})

def faseListaSiembra(request,idSiembra):
	smb = siembra.objects.get(id=idSiembra)
	fase = faseCultivo.objects.filter(siembra=smb.nombre)
	return render(request,'administrar/faseCultivo.html',{'fase':fase})


def siembras(request):
	if request.method == 'POST':
		sm = siembra()
		sm.nombre = request.POST['nombre']
		sm.descripcion = request.POST['descripcion']
		sm.estado = 1
		sm.save()
		return redirect('admi:siembra')
	sm2 =  siembra.objects.all().order_by('id')
	return render(request,'administrar/siembra.html',{'siembra':sm2})

def listaUsuarios(request):
	usua = usuario.objects.filter(estado=1).order_by('id')

	return render(request,'administrar/listaUsuario.html',{'usuario':usua})

def bloquearUsuario(request,idusuario):
	usua = usuario.objects.get(id=idusuario)
	usua.estado = 0
	usua.save()
	return redirect('admi:listaUsuarios')

def usuariosBloqueados(request):
	usua = usuario.objects.filter(estado=0).order_by('-id')

	return render(request,'administrar/listaUsuario.html',{'usuario':usua})

def habilitarUsuario(request,idusuario):
	usua = usuario.objects.get(id=idusuario)
	usua.estado = 1
	usua.save()
	return redirect('admi:usuariosBloqueados')

def verUsuario(request,idusuario):
	usua = usuario.objects.get(id=idusuario)
	return render(request,'administrar/verUsuario.html',{'usuario':usua})

#---------------------------------------------------------------------------------
#Fase de cultivo
@csrf_protect
def nuevaFase(request):
	
	if request.method == 'POST':
		fc = faseCultivo()
		fc.etapa = request.POST['etapa']
		fc.descripcion = request.POST['descripcion']
		fc.diasDuracion = request.POST['diasD']
		fc.hidricos = request.POST['hidricos']
		fc.siembra = request.POST['siembra']
		fc.estado = 1
		fc.save()
		return redirect('admi:faseCultivo')
	siembras = siembra.objects.filter(estado=1)
	return render(request,'administrar/nuevoFaseCultivo.html',{'siembras':siembras})

# Create your views here.

apps/login/views.py
from django.shortcuts import render,redirect
from django.http import *
from django.contrib.auth import *
from django.contrib.auth.models import *
from django.template import loader
from django.views.defaults import page_not_found
from apps.administrar.models import *
from django.contrib.auth.hashers import make_password,check_password

def login(request):
	if request.user.is_active:
		return redirect('admi:inicio')
	error=' '
	if request.method == 'POST':
		email2 = request.POST.get('email',None)
		con = request.POST.get('password',None)
		#con2 = make_password(con,hasher='pbkdf2_sha256')
		us = usuario.objects.filter(email=email2).exists()
		if us == True:
			us = usuario.objects.get(email=email2)
			nombre = us.nombre
			con2 = us.password
			tiusu = us.tipoU.id 
			con3 = check_password(con,con2,setter=None,preferred='default')
			if con3 == True:
				usn=""
				usn+=nombre
				usn+=email2
				user=auth.authenticate(username=usn,email=email2,password=con)
				if user:
					auth.login(request,user)
					if tiusu == 1:
						return redirect('admi:inicio')
					else:
						return redirect('simular:index')
				else:
					error="Error de autentificacion"
					return render(request,'administrar/login.html',{'error':error})
			else:
				error="Password incorrecto"
				return render(request,'administrar/login.html',{'error':error})
		else:
			error = "Email no valido o mal digitado"
			return render(request,'administrar/login.html',{'error':error})
	else:
		error=" "
		template = loader.get_template('administrar/login.html')
		contexto = {'error':error}
		return render(request,'administrar/login.html',contexto)
		#return HttpResponse(template.render(context,request))

def logout(request):
	auth.logout(request)
	return HttpResponseRedirect("/")


def registrar(request):
	error = ''
	year=('1930','1931','1932','1933','1934','1935','1936','1937','1938','1939',
	'1940','1941','1942','1943','1944','1945','1946','1947','1948','1949',
	'1950','1951','1952','1953','1954','1955','1956',
	'1957','1958','1959','1961','1962','1963','1964','1965',
	'1966','1967','1968','1969','1970','1971','1972','1973','1974','1975',
	'1976','1977','1978','1979',
	'1980','1981','1982','1969','1983','1984','1985','1986','1987','1988','1989',
	'1990','1991','1992','1993','1994','1995','1996','1997','1998','1999',
	'2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010',
	)
	mes = ('Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre')
	dia = ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31')
	sexos = (('Masculino','Masculino'),('Femenino','Femenino'))
	tipou = tipoUsuario.objects.filter(estado=1).order_by('id')
	if request.method == 'POST':
		email2 = request.POST.get('email',None)

		if User.objects.filter(email=email2).exists() == False:
			usua = usuario()
			nom = request.POST['nombre']
			usua.nombre = nom
			usua.apellido = request.POST['apellido']
			passw = request.POST['password']
			usua.password = make_password(passw,hasher='pbkdf2_sha256')
			anio = request.POST['anio']
			mes2 = request.POST['mes']
			mesNum = mesNumerico(mes2)
			dia2 = request.POST['dia']
			fecha=anio
			fecha+= "-"
			fecha+=mesNum
			fecha+="-"
			fecha+=dia2
			usua.fechaNacimiento = fecha
			sexo2 = request.POST['sexo']
			if sexo2 == "0":
				usua.sexo = "Masculino"
			else:
				usua.sexo = "Femenino"
			email2 = request.POST['email']
			usua.email = email2
			idTipoU = request.POST['tipou']
			usua.tipoU = tipoUsuario.objects.get(id=idTipoU)
			usua.estado = 1
			usua.save()
			nom2=''
			nom2+=nom
			nom2+=email2
			user = User.objects.create_user(username=nom2,email=email2,password=passw)
			user=authenticate(email=email2,password=passw)
			login(request)
			return redirect('admi:inicio')	
		else:
			error="El correo ya existe"
			return render(request,'administrar/registrar.html',{'error':error,'tipo':tipou,'year':year,'mes':mes,'dia':dia,'sexo':sexos})
	else:
		error=' '
		return render(request,'administrar/registrar.html',{'error':error,'tipo':tipou,'year':year,'mes':mes,'dia':dia,'sexo':sexos})


def mesNumerico(dato):
	mm = ''
	if dato == 'Enero':
		mm = '1'
	if dato == 'Febrero':
		mm = '2'
	if dato == 'Marzo':
		mm = '3'
	if dato == 'Abril':
		mm = '4'
	if dato =='Mayo':
		mm = '5'
	if dato == 'Junio':
		mm = '6'
	if dato == 'Julio':
		mm = '7'
	if dato == 'Agosto':
		mm = '8'
	if dato == 'Septiembre':
		mm = '9'
	if dato == 'Octubre':
		mm = '10'
	if dato == 'Noviembre':
		mm = '11'
	if dato == 'Diciembre':
		mm = '12'
	return mm 
		#return redirec('login:registro')

templates/administrar/faseCultivo.html
{% extends 'base/baseAdmin.html' %}
{% load staticfiles %}

{% block title %}Fase de cultivo{% endblock %}

{% block content %}
<div class="panel panel-info">
    <div class="panel-heading">
    <div class="container text-center">
      <h1>LISTADO DE FASES DE CULTIVO</h1>   
    </div>
    </div>
  </div>
<div class="container">
    <a href="{% url 'admi:nuevaFase'%}" class="btn btn-primary ">Nuevo</a>
</div>

<div class="container">           
  <table id="listaCa" class="table table-bordered btn-hover">
    <thead>
      <tr>
        <th >#</th>
        <th>Etapa</th>
        <th>Descripcion</th>
        <th>Dias de duracion</th>
        <th>Hidricos</th>
        <th>siembra<span class="glyphicon glyphicon-sort"></span></th>
        <th>Estado<span class="glyphicon glyphicon-sort"></span></th>
        <th>Accion</th>
      </tr>
    </thead>
    <tbody>
    	{% if fase %}
    	{% for fases in fase %}
      {% if fases.estado == 1%}
      <tr class="success">
        <td>{{fases.id}}</td>
        <td>{{fases.etapa}}</td>
        <td>{{fases.descripcion}}</td>
        <td>{{fases.diasDuracion}}</td>
        <td>{{fases.hidricos}}</td>
        <td>{{fases.siembra}}</td>
        <td><strong>Habilitado</strong></td>
        <td>
        	<a class="btn btn-primary" href="">Editar</a>
			    <a class="btn btn-danger" href="">Eliminar</a>
			    <a class="btn btn-info" href="">Habilitar</a>
        </td>
      </tr>
       {% else %}
        <tr class="danger">
        <td>{{fases.id}}</td>
        <td>{{fases.etapa}}</td>
        <td>{{fases.descripcion}}</td>
        <td>{{fases.diasDuracion}}</td>
        <td>{{fases.hidricos}}</td>
        <td>{{fases.siembra}}</td>
        <td><strong>Deshabilitado</strong></td>
        <td>
          <a class="btn btn-primary" href="">Editar</a>
          <a class="btn btn-danger" href="">Eliminar</a>
          <a class="btn btn-info" href="">Habilitar</a>
        </td>
      </tr>
       {% endif %}
      {% endfor %}
      {% else %}
      <h1>No existe registro alguno</h1>
      {% endif %}
    </tbody>
  </table>
</div>

<script>
$(document).ready(function () {
$('#listaCa').DataTable({
    "language":{
        "lengthMenu":"Mostrar _MENU_ registro por pagina",
        "zeroRecords":"No se encontraron resultados en la busqueda",
        "searchPlaceholder":"Buscar registros",
        "info":"Mostrando registros de _START_ al _END_ de un total de _TOTAL_ registros",
        "infoEmpty":"No existen registros",
        "infoFiltered":"(filtrado de un total de _MAX_ registros)",
        "search":"Buscar:",
        "paginate":{
            "first":"Primero",
            "last":"Ultimo",
            "next":"Siguiente",
            "previous":"Anterior"
        },
    }
});
$('.sidebar-menu').tree();
});
</script>

{% endblock %}

templates/administrar/listaUsuario.html
{% extends 'base/baseAdmin.html'%}

{% load staticfiles %}

{% block title %} Listado usuarios{% endblock %}

{%block content %}
<div class="container">           
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Sexo</th>
        <th>Tipo Usuario</th>
        <th>Estado</th>
        <th>Accion</th>
      </tr>
    </thead>
    <tbody>
    	{% if usuario %}
    	{% for usuarios in usuario %}

      <tr>
      	<td>{{usuarios.id}}</td>
        <td>{{usuarios.nombre}}</td>
        <td>{{usuarios.apellido}}</td>
        <td>{{usuarios.sexo}}</td>
        <td>{{usuarios.tipoU.descripcion}}</td>
        {% if usuarios.estado == 1 %}
        	<td><strong>Habilitado</strong></td>
        {% else %}
        	<td><strong>Deshabilitado</strong></td>
        {% endif %}
        <td>
        	<a class="btn btn-primary" href="{% url 'admi:verusuario' usuarios.id%}">Ver</a>
        {% if usuarios.estado == 1%}
			<a class="btn btn-danger" href="{% url 'admi:bloquearUsuario' usuarios.id %}">Bloquear</a>
        {% else %}
        	<a class="btn btn-success" href="{% url 'admi:habilitarUsuario' usuarios.id %}">Habilitar</a>
        {% endif %}
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <h1>No existe registro alguno</h1>
      {% endif %}
    </tbody>
  </table>
</div>




{% endblock %}

templates/administrar/login.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<title>Login</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "css/main.css" %}" />
		<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:400,700">

	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<h1>Simulador</h1>
				<p>Software para el desarrollo de Simulaciones<br />
				de Siembra y Cultivo </p>
			</header>

		<!-- Signup Form -->
			{{error}}

			<form id="signup-form" method="POST" >
				{% csrf_token %}
				<input type="email" name="email" id="email" placeholder="Email Address" style="width: 290px" required >
				<br/>
				<input type="password" name="password" id="password" placeholder="password" required />
				<br/>
				<input type="submit" value="Sign Up" />
			
			</form>
		<!-- Footer -->
			<footer id="footer">

				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
					<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">facebook</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; Untitled.</li><li>Credits: <a href="http://html5up.net">HTML5 UP</a></li><li><a href="{% url 'login:registro' %}">Crea una cuenta</a></li>
				</ul>
			</footer>

		<!-- Scripts -->
			<script type="text/javascript" src="/static/js/main4.js"></script>
			

	</body>
</html>

templates/administrar/nuevoFaseCultivo.html
{% extends 'base/baseAdmin.html' %}
{% load staticfiles %}

{% block title %}Nueva fase de cultivo{% endblock %}

{% block content %}

<form class="form-horizontal"  method="POST" >

	<div class="panel panel-info">
		<div class="panel-heading">
		<div class="container text-center">
			<h1>FORMULARIO DE FASES DE CULTIVO</h1>		
		</div>
		</div>
	</div>
{% csrf_token %}
	<div class="form-group">
		<label for="etapa" class="col-sm-2 control-label">Etapa:</label>
		<div class="col-sm-3">
			<input type="text" name="etapa" id="etapa" class="form-control" placeholder="Etapa..">
		</div>
	</div>
	<div class="form-group">
		<label for="descripcion" class="col-sm-2 control-label">Descripcion:</label>
		<div class="col-sm-5">
			<input type="textarea" name="descripcion" id="descripcion" class="form-control" placeholder="Descripcion..">
		</div>
	</div>
	<div class="form-group">
		<label for="diasD" class="col-sm-2 control-label">Dias de duracion:</label>
		<div class="col-sm-3">
			<input type="range" name="diasD" id="diasD" min="1" max="100" step="1">
		</div>
		<div class="col-sm-3">
			<input type="text" name="valor" id="valor" disabled placeholder="dias..">
		</div>
	</div>
	<div class="form-group">
		<label for="hidricos" class="col-sm-2 control-label">Hidricos:</label>
		<div class="col-sm-3">
			<input type="range" name="hidricos" id="hidricos" min="1" max="100" step="0.01">
		</div>
		<div class="col-sm-3">
			<input type="text" name="valor2" id="valor2" disabled placeholder="hidricos..">
		</div>
	</div>
	<div class="form-group">
		<label for="siembra" class="col-sm-2 control-label">Siembra:</label>
		<div class="col-sm-4">
			<select style="width:100px" name="siembra">
				{%for siembra in siembras %}
				<option value="{{siembra.nombre}}">{{siembra.nombre}}</option>
				{% endfor %}
			</select>
		</div>
		
	</div>
	<br>
	<div class="container">
		<button class="btn btn-primary">Guardar</button>
		<a href="{% url 'admi:faseCultivo' %}" class="btn btn-danger">Cancelar</a>	
	</div>

</form>

<script type="text/javascript">
	$(document).ready(function(){
	
		$('#diasD').change(function() {
		$('#valor').val($(this).val());
		});
		$('#hidricos').change(function() {
		$('#valor2').val($(this).val());
		});
	});
	
</script>

{% endblock %}

templates/administrar/registrar.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<title>Registrar</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static "css/main.css" %}" />

	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<h1>Simulador</h1>
				<p>Registrate Ahora </p>
			</header>

		<!-- Signup Form -->

			<form id="signup-form" method="POST" >
				{% csrf_token %}
				<input type="text" name="nombre" id="nombre" placeholder="nombre" required />
				
				<input type="text" name="apellido" id="apellido" placeholder="apellido" required />
				<br/>
				<input type="email" name="email" id="email" placeholder="Email Address" required style="width: 290px" />
				{{error}}
				<input type="password" name="password" id="password" placeholder="password" required />
				<br/>
				<label>Fecha Nacimiento</label>
				<select style="width:100px" name="anio" >
					{% for anio in year %}
					<option value="{{anio}}" >{{anio}}</option>
					{% endfor %}
				</select>
				
				<select style="width:150px" name="mes">
					{% for meses in mes %}
					<option value="{{meses}}">{{meses}}</option>
					{% endfor %}
				</select>
				
				<select style="width:100px" name="dia">
					{% for dias in dia %}
					<option value="{{dias}}">{{dias}}</option>
					{% endfor %}
				</select>
				<br/>
				
				<label>Sexo</label>
				<select style="width: 170px" name="sexo" > 
					<option value="0">Masculino</option>
					<option value="1">Femenino</option>
				</select>
				<label>Profesion</label>
				<select name="tipou" id="tipou" style="width:150px" >
					{% for tipos in tipo %}
					{% if tipos.id > 1%}
					<option value="{{tipos.id}}" >{{tipos.descripcion}}</option>
					{% endif %}
					{% endfor %}
				</select>
				 	
				<br/> 
				
				<input type="submit" value="Guardar" />
			
			</form>
		<!-- Footer -->
			<footer id="footer">

				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
					<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">facebook</span></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; Untitled.</li><li>Credits: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</footer>

		<!-- Scripts -->
			<script type="text/javascript" src="/static/js/main4.js"></script>
			

	</body>
</html>

templates/administrar/siembra.html
{% extends 'base/baseAdmin.html' %}
{% load staticfiles %}

{% block title %}Siembras{% endblock %}

{% block content %}
<div class="container">
  <form class="form-inline" method="POST" >
  {% csrf_token %}
    <div class="form-group">
      <label class="sr-only" for="descripcion">Nombre:</label>
      <input type="nombre" class="form-control" id="nombre" placeholder="Ingrese siembra"  name="nombre" required="required">
      <label class="sr-only" for="descripcion">Descripcion:</label>
      <input type="tipoUsuario" class="form-control" id="descripcion" placeholder="Ingrese descricpion"  name="descripcion" required="required">
    </div>
    <button type="submit" class="btn btn-primary ">Guardar</button>
  </form>
</div>

<div class="container">           
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>Accion</th>
      </tr>
    </thead>
    <tbody>
    	{% if siembra %}
    	{% for siembras in siembra %}

      <tr>
        <td>{{siembras.id}}</td>
        {% if siembras.estado == 1 %}
        <td><a href="{% url 'admi:faseCultivoSiembra' siembras.id%}">{{siembras.nombre}}</a></td>
        {% else %}
        <td>{{siembras.nombre}}</td>
        {% endif %}
        <td>{{siembras.descripcion}}</td>
        {% if siembras.estado == 1 %}
        <td><strong>Habilitado</strong></td>
        {%else%}
        <td><strong>Deshabilitado</strong></td>
        {%endif%}
        <td>
        	<a class="btn btn-primary" href="">Editar</a>
			<a class="btn btn-danger" href="">Eliminar</a>
			<a class="btn btn-info" href="">Habilitar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <h1>No existe registro alguno</h1>
      {% endif %}
    </tbody>
  </table>
</div>

{% endblock %}

templates/administrar/tipoUsuario.html
{% extends 'base/baseAdmin.html'%}
{% load staticfiles %}

{% block title %}Tipos de usuario{% endblock %}

{% block content %}
<div class="container">
	
	<form class="form-inline" method="POST" >
	{% csrf_token %}
    <div class="form-group">
      <label class="sr-only" for="descripcion">Descripcion:</label>
      <input type="tipoUsuario" class="form-control" id="descripcion" placeholder="Ingrese tipo de usuario"  name="descripcion" required="required">
    </div>
    <button type="submit" class="btn btn-primary ">Guardar</button>
  </form>
</div>


<div class="container">           
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>#</th>
        <th>Descripcion</th>
        <th>Estado</th>
        <th>Accion</th>
      </tr>
    </thead>
    <tbody>
    	{% if tipo %}
    	{% for tipos in tipo %}

      <tr>
        <td>{{tipos.id}}</td>
        <td>{{tipos.descripcion}}</td>
        {% if tipos.estado == 1 %}
        <td><strong>Habilitado</strong></td>
        {%else%}
        <td><strong>Deshabilitado</strong></td>
        {%endif%}
        <td>
        	<a class="btn btn-primary" href="">Editar</a>
			<a class="btn btn-danger" href="{%url 'admi:eliminarTipo' tipos.id %}">Eliminar</a>
			<a class="btn btn-info" href="{%url 'admi:habilitarTipo' tipos.id %}">Habilitar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <h1>No existe registro </h1>
      {% endif %}
    </tbody>
  </table>
</div>


{% endblock %}

templates/administrar/verUsuario.html
{% extends 'base/baseAdmin.html' %}

{% load staticfiles %}

{% block title %}Informacion de usuarios{% endblock %}

{% block content%}
<h2>Nombre:{{usuario.nombre}}</h2>
<h2>Apellido:{{usuario.apellido}}</h2>
<h2>Fecha de nacimiento:{{usuario.fechaNacimiento}}</h2>
<h2>Sexo:{{usuario.sexo}}</h2>
<h2>Email:{{usuario.email}}</h2>
<h2>Tipo de usuario:{{usuario.tipoU.descripcion}}</h2>

{% endblock %}